version: "3.9"

services:
  postgres:
    hostname: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    command: [ "postgres", "-c", "log_statement=all" ]

  init-db:
    build:
      context: .
      dockerfile: init/Dockerfile
    env_file:
      - .env

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg-data: